# Deployment hostname with full domain, but without protocol
hostname: 
 

################################################################################
# InterLink configuration

# serverVersion is the version of the interlink release to retrieve from GitHub
serverVersion: 0.3.0

# serverPort is the internal port number to access the interLink server
serverPort: 30080

# sidecarName is the name of the service used to access the sidecar 
sidecarName: condor-plugin

# sidecarPort is the exposed port of the sidecar
sidecarPort: 80

# serverVerboseLogging if true enhance verbosity of the server
serverVerboseLogging: true

# serverErrorsOnlyLogging if true reduces the verbosity of the server
serverErrorsOnlyLogging: false

# serverExportPodData
serverExportPodData: true

  
################################################################################
# Ingress configuration

# serverPathPrefix is the reverse-proxy path prefix to reach server. WITHOUT SLASHES.
serverPathPrefix: condor

# certManagerEnabled if true, set up a certmanager for TLS termination
# IMPORTANT!!! Disable it if installing the chart in an already certified cluster
certManagerEnabled: true


# certManagerEmailAddress is the email address of the certificate owner
certManagerEmailAddress: 
 

################################################################################
# Authentication configuration

# oauth2ProxyImage is the docker image of the oauth2-proxy service
oauth2ProxyImage: "quay.io/oauth2-proxy/oauth2-proxy:v7.6.0"

# iamClientId is the Client ID of the IAM OIDC token issuer
oauth2ProxyIamClientId:

# iamClientSecret is the Client Secret of the IAM OIDC token issuer
oauth2ProxyIamClientSecret:

# oauth2ProxyPort is the internal port of the oauth2-proxy service
oauth2ProxyPort: 8000

# oauth2ProxyIamIssuer is the path to the IAM issuer passed to the oauth2-proxy
oauth2ProxyIamIssuer: "https://iam.cloud.infn.it/"

# oauth2ProxyTokenUrl is the path to the IAM issuer passed to the oauth2-proxy
oauth2ProxyTokenUrl: "https://iam.cloud.infn.it/token"

# oauth2ProxyIamGroupClaim is the json path in the returned token to retrieve the user's groups
oauth2ProxyIamGroupClaim: groups

# oauth2ProxyIamAllowedGroup is the IAM group whose user can access the interlink server
oauth2ProxyIamAllowedGroup: admins

# oauth2ProxyAudience is the audience in the token. Should be consistent with client setup
oauth2ProxyAudience: users
 
# oauth2ProxyCookieSecret is a random string used to encrypt the cookies
oauth2ProxyCookieSecret: 
 
################################################################################
# Plugin configuration

# pluginDocker image where to download from GitHub and run the condor-ce plugin
pluginDocker: "landerlini/interlink-condorce-plugin:v0.0"

# pluginRepository is the git repository of the plugin, kept updated with git-sync
pluginRepository: "https://github.com/landerlini/interlink-condorce-plugin"

# pluginLivenessInitialDelaySeconds is the initial delay before prompting the plugin healthz.
pluginLivenessInitialDelaySeconds: 2
 
# pluginLivenessProbePeriodSeconds is the period ot ping to healtz 
pluginLivenessProbePeriodSeconds: 10

# pluginGitSyncPeriod is the frequency of the polling to git repository for updates
# As a rule of thumb, you can use a large value in production and shorten it for 
# faster turn-over while debugging. 
pluginGitSyncPeriod: 10s

# pluginLogLevel is the log level of uvicorn 
# see https://www.uvicorn.org/settings/#logging
pluginLogLevel: info

# pluginDebug enables additional debug messages and disable optimizations
pluginDebug: "true"

# pluginTokenValiditySeconds defines for how many seconds the token is considered as valid after refresh
pluginTokenValiditySeconds: 1200

# pluginCondorPool is the HTCondor collector, usually passed as value of the argument -pool to condor CLI
pluginCondorPool: "ce01t-htc.cr.cnaf.infn.it:9619"

# pluginSchedulerName is the HTCondor scheduler, usually passed as value of the argument -name to condor CLI
pluginCondorScheduler: "ce01t-htc.cr.cnaf.infn.it"

# backendIamIssuer is the IAM issuer to authenticate against the HTCondor backend (via scitokens)
backendIamIssuer: "https://iam-t1-computing.cloud.cnaf.infn.it"

# backendIamClientId is the ClientID of the IAM used to authenticate against the HTCondor backend (via scitokens)
backendIamClientId:

# backendIamClientSecret is the Client password of the IAM used to authenticate against the HTCondor backend (scitokens)
backendIamClientSecret:

# backendIamAudience is the audience for the refreshed token (virtual-kubelet-inttw-refresh image)
backendIamAudience: users

# backendIamGrantType is the grant_type for the token refresher (virtual-kubelet-inttw-refresh image)
backendIamGrantType: authorization_code

# backendRefreshTokenCpuLimit is the limit to the cpu of the refresh-token service
backendRefreshTokenCpuLimit: 200m

# backendRefreshTokenMemoryLimit is the memory limit for the refresh-token servce
backendRefreshTokenMemoryLimit: 500Mi

# backendRefreshTokenCpuLimit is the limit to the cpu of the refresh-token service
backendRefreshTokenCpuRequest: 10m

# backendRefreshTokenMemoryLimit is the memory limit for the refresh-token servce
backendRefreshTokenMemoryRequest: 100Mi


# backendIamScope lists the scopes requested to the IAM
backendIamScopes:
  - openid
  - profile
  - offline_access
  - wlcg.groups
  - wlcg
  - compute.create
  - compute.modify
  - compute.read
  - compute.cancel

