{{ if .Values.kueueNatsEnabled }}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: kueue-nats-controller-account
  namespace: {{ .Release.Namespace }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-queue-manager
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [vk.io]
    resources: [masterqueues]
    verbs: [list, watch, patch, get]

  - apiGroups: [kueue.x-k8s.io]
    resources: [clusterqueues, resourceflavors]
    verbs: [list, create, update, patch, get, delete]

  # Framework: runtime observation of namespaces & CRDs (addition/deletion).
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, watch]
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [list, watch]
  - apiGroups: [ "" ]
    resources: [ events ]
    verbs: [ create ]


  # Framework: admission webhook configuration management.
  - apiGroups: [admissionregistration.k8s.io/v1, admissionregistration.k8s.io/v1beta1]
    resources: [validatingwebhookconfigurations, mutatingwebhookconfigurations]
    verbs: [create, patch]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-queue-manager-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-queue-manager
subjects:
  - kind: ServiceAccount
    name: kueue-nats-controller-account
    namespace: {{ .Release.Namespace }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kueue-nats-controller
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: kueue-nats-controller
  template:
    metadata:
      labels:
        app: kueue-nats-controller
    spec:
      serviceAccountName: kueue-nats-controller-account
      restartPolicy: Always
      containers:
        - name: kopf
          image: landerlini/kueue-nats-controller
          imagePullPolicy: Always



{{ end }}
