apiVersion: v1
kind: Pod
metadata: 
  name: authenticate-{{ .Values.nodeName }} 
  namespace: {{ .Release.Namespace }} 

spec: 
  serviceAccountName: {{ .Values.nodeName }}-authenticator
  containers:
    - name: authenticator
      image: {{ .Values.authenticatorImage | default "landerlini/interlink-virtual-node-authenticator:latest" }}
      imagePullPolicy: Always
      command: ["sleep", "infinity"]
      env:
        - name: CLIENT_ID
          value: {{ .Values.iamClientId }}
        - name: CLIENT_SECRET
          value: {{ .Values.iamClientSecret }}
        - name: DEVICECODE_URL
          value: {{ .Values.iamDeviceCodeEndpoint | default "https://iam.cloud.infn.it/devicecode" }}
        - name: TOKEN_URL
          value: {{ .Values.iamTokenEndpoint | default "https://iam.cloud.infn.it/token" }}
        - name: SCOPES
          value: {{ .Values.iamScopes | toJson | squote }}
        - name: SECRET_NAMESPACE
          value: {{ .Release.Namespace }}
        - name: SECRET_NAME 
          value: {{ .Values.nodeName }}-token

      resources:
        limits:
          cpu: {{ .Values.authenticatorCpuLimit | default "1000m" }}
          memory: {{ .Values.authenticatorMemoryLimit | default "1Gi" }}
        requests:
          cpu: {{ .Values.authenticatorCpuRequest | default "0" }}
          memory: {{ .Values.authenticatorMemoryRequest | default "0" }}


---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.nodeName }}-authenticator
  namespace: {{ .Release.Namespace }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.nodeName }}-authenticator
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.nodeName }}-authenticator
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.nodeName }}-authenticator

--- 

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.nodeName }}-authenticator
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - update
  - patch

