################################################################################
## Container plugin

apiVersion: v1
kind: ConfigMap
metadata:
  name: condor-build-conf
  namespace: {{ .Release.Namespace }}
data:
  interlink.conf: |
    # Volumes and directories configuring access to executor-local data
    [volumes]

    ### Area in the executor filesystem to be used for temporary files
    scratch_area = "/tmp"

    ### Location to cache singularity images in the executor filesystem
    apptainer_cachedir = "/tmp/cache/apptainer"

    ### Location where to look for pre-built images
    image_dir = {{ .Values.backendLocalImageDir | default "/opt/exp_software/opssw/budda" | toJson }}

    ### Colon-separated list of directories to include in $PATH to look for executables
    additional_directories_in_path = ["/opt/exp_software/opssw/mabarbet/bin"]



    # Options configuring the behavior of apptainer runtime
    [apptainer]

    ### Enables --fakeroot in apptainer exec/run commands
    fakeroot = false

    ### Enables --containall flag in apptainer exec/run commands
    containall = false

    ### Defines whether the host enables users to mount fuse volumes or not
    fuse_enabled_on_host = true

    ### Do not propagate umask to the container, set default 0022 umask
    no_init = true

    ### Do not bind home by default
    no_home = true

    ### Drop all privileges from root user in container
    no_privs = true

    ### Enable nVidia GPU support
    nvidia_support = false

    ### Clean the environment of the spawned container
    cleanenv = true



    # Proxy to download pre-build Docker Images instead of rebuilding at each execution
    [shub_proxy]

    ### shub proxy instance used to retrieve cached singularity images. Without protocol!
    server = {{  .Values.backendShubProxy | required "Please define backendShubProxy" | toJson }}

    ### Master token of the proxy used to request and generate client tokens
    master_token = {{  .Values.backendShubProxyMasterToken | required "Please define backendShubProxyMasterToken" | toJson }}


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-plugin
  namespace: {{ .Release.Namespace }}
  labels:
    app: interlink
    component: condor-plugin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interlink
      component: condor-plugin
  template:
    metadata:
      labels:
        app: interlink
        component: condor-plugin
    spec:
      securityContext:
        # Copy-pasted from https://github.com/kubernetes/git-sync/blob/master/docs/kubernetes.md
        fsGroup: 101

      containers:
        - name: fastapi-server
          image: {{ .Values.pluginDockerImage | default "landerlini/interlink-condorce-plugin:v0.1" }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              cd /interlink/current
              python3 -m uvicorn natsplugin:app --reload --host 0.0.0.0 --log-level={{ .Values.pluginLogLevel | default "info" }} --port 8000

          env:
            - name: DEBUG
              value: {{ .Values.pluginDebug | default "true" | quote }}
          ports:
            - containerPort: 8000

          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: {{ .Values.pluginLivenessInitialDelaySeconds | default 3  }}
            periodSeconds: {{ .Values.pluginLivenessProbePeriodSeconds | default 3  }}

          volumeMounts:
            - name: interlink
              mountPath: /interlink
              readOnly: true

        - name: condorprovider
          image: {{ .Values.pluginDockerImage | default "landerlini/interlink-condorce-plugin:v0.1" }}
          command: ["/bin/sh", "-c"]
          args: 
            - |
              sleep 5
              cd /interlink/current
              python3 -m natsprovider condor \
                  --queue {{ .Values.natsQueue | default "condor" }} \
                  --shutdown-subject {{ .Values.natsShutdownSubject | default "condor" }} \
                  --non-interactive

          env:
            - name: DEBUG
              value: {{ .Values.pluginDebug | default "true" | quote }}
            - name: TOKEN_VALIDITY_SECONDS
              value: {{ .Values.pluginTokenValiditySeconds | default 1200 | quote }}
            - name: CONDOR_POOL
              value: {{ .Values.pluginCondorPool | required "pluginCondorPool is missing (value for -pool arg)" }}
            - name: CONDOR_SCHEDULER_NAME
              value: {{ .Values.pluginCondorScheduler | required "pluginCondorPool is missing (value for -name arg)" }}
            - name: IAM_ISSUER
              value: {{ .Values.backendIamIssuer | required "backendIamIssuer is missing (this is the condor IAM)"}}
            - name: IAM_CLIENT_ID
              value: {{ .Values.backendIamClientId | required "backendIamClientId is missing (this is the condor IAM)"}}
            - name: IAM_CLIENT_SECRET
              value: {{ .Values.backendIamClientSecret | required "backendIamClientSecret is missing (this is the condor IAM)"}}
            - name: BEARER_TOKEN_PATH
              value: /interlink/token
            - name: NATS_SUBJECT
              value: {{ .Values.natsSubject | default "interlink" }}
            - name: NATS_SERVER
              value: {{ .Values.natsServer | default "nats://nats:4222" }}
            - name: NATS_TIMEOUT_SECONDS
              value: {{ .Values.natsTimeoutSeconds | default 60 | quote }}

          volumeMounts:
            - name: interlink
              mountPath: /interlink
              readOnly: true

        - name: git-sync
          image: registry.k8s.io/git-sync/git-sync:v4.2.4
          args:
            - --repo={{ .Values.pluginRepository | default "https://github.com/landerlini/interlink-condorce-plugin" }}
            - --ref={{ .Values.pluginRepositoryBranch | default "HEAD" }}
            - --period={{ .Values.pluginGitSyncPeriod | default "5s" }}
            - --link=current
            - --root=/interlink
            - --webhook-url=http://localhost:8000/shutdown/{{ .Values.natsShutdownSubject | default "condor" }}

          volumeMounts:
            - name: interlink
              mountPath: /interlink

          resources:
            limits:
              memory: 1Gi
            requests:
              memory: 1Gi

        - name: refresh-token
          image: {{ .Values.inttwRefreshTokenImage | default "ghcr.io/intertwin-eu/interlink/virtual-kubelet-inttw-refresh:latest" }}
          imagePullPolicy: Always
          env:
            - name: IAM_TOKEN_ENDPOINT
              value: "{{ .Values.backendIamIssuer }}/token"
            - name: IAM_CLIENT_ID
              value: {{ .Values.backendIamClientId | required "Please provide `iamClientId`" }}
            - name: IAM_CLIENT_SECRET
              value: {{ .Values.backendIamClientSecret | required "Please provide `iamClientSecret`" }}
            - name: IAM_GRANT_TYPE
              value: {{ .Values.backendIamGrantType | default "authorization_code" }}
            - name: IAM_REFRESH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-token
                  key: refresh-token
            - name: IAM_VK_AUD
              value: {{ .Values.backendIamAudience | default "users" }}
            - name: TOKEN_PATH
              value: /interlink/token
          command:
            - python3
            - /opt/refresh.py

          resources:
            limits:
              cpu: {{ .Values.backendRefreshTokenCpuLimit | default "200m" }}
              memory: {{ .Values.backendRefreshTokenMemoryLimit | default "500Mi" }}
            requests:
              cpu: {{ .Values.backendRefreshTokenCpuRequest  | default "10m" }}
              memory: {{ .Values.backendRefreshTokenMemoryRequest | default "100Mi" }}
          volumeMounts:
            - name: interlink
              mountPath: /interlink

      volumes:
        - name: interlink
          emptyDir:
            sizeLimit: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  name: condor-plugin
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: interlink
    component: condor-plugin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000


