################################################################################
## Container plugin


apiVersion: apps/v1
kind: Deployment
metadata:
  name: condor-plugin
  namespace: {{ .Release.Namespace }}
  labels:
    app: interlink
    component: condor-plugin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interlink
      component: condor-plugin
  template:
    metadata:
      labels:
        app: interlink
        component: condor-plugin
    spec:
      serviceAccount: condor-plugin
      securityContext:
        # Copy-pasted from https://github.com/kubernetes/git-sync/blob/master/docs/kubernetes.md
        fsGroup: 101

      containers:
        - name: git-sync
          image: registry.k8s.io/git-sync/git-sync:v4.0.0
          args: 
            - --repo={{ .Values.pluginRepository | default "https://github.com/landerlini/interlink-condorce-plugin" }}
            - --period={{ .Values.pluginGitSyncPeriod | default "5s" }}
            - --link=current
            - --root=/interlink
            - --webhook-url=http://localhost:8000/shutdown

          volumeMounts:
            - name: interlink
              mountPath: /interlink

        - name: interlink
          image: {{ .Values.pluginDockerImage | default "landerlini/interlink-condorce-plugin:v0.0" }}
          command: ["/bin/sh", "-c"]
          args: 
            - |
              cd /interlink/current
              python3 -m uvicorn main:app --reload --host 0.0.0.0 --log-level={{ .Values.pluginLogLevel | default "info" }} --port 8000

          env:
            - name: DEBUG
              value: {{ .Values.pluginDebug | default "true" | quote }}
            - name: TOKEN_VALIDITY_SECONDS
              value: {{ .Values.pluginTokenValiditySeconds | default 1200 | quote }}
            - name: CONDOR_POOL
              value: {{ .Values.pluginCondorPool | required "pluginCondorPool is missing (value for -pool arg)" }}
            - name: CONDOR_SCHEDULER_NAME
              value: {{ .Values.pluginCondorScheduler | required "pluginCondorPool is missing (value for -name arg)" }}
            - name: IAM_ISSUER
              value: {{ .Values.backendIamIssuer | required "backendIamIssuer is missing (this is the condor IAM)"}}
            - name: IAM_CLIENT_ID
              value: {{ .Values.backendIamClientId | required "backendIamClientId is missing (this is the condor IAM)"}}
            - name: IAM_CLIENT_SECRET
              value: {{ .Values.backendIamClientSecret | required "backendIamClientSecret is missing (this is the condor IAM)"}}

          ports:
            - containerPort: 8000

          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: {{ .Values.pluginLivenessInitialDelaySeconds | default 3  }} 
            periodSeconds: {{ .Values.pluginLivenessProbePeriodSeconds | default 3  }}


          volumeMounts:
            - name: interlink
              mountPath: /interlink
              readOnly: true

      volumes:
        - name: interlink
          emptyDir:
            sizeLimit: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  name: condor-plugin
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: interlink
    component: condor-plugin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000


